# Generated by Django 3.0.1 on 2019-12-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('meeting_id', models.CharField(max_length=40)),
                ('meeting_name', models.TextField(default='meeting 1')),
                ('group_id', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('count', models.IntegerField(blank=True, max_length=4)),
            ],
            options={
                'db_table': 'meetings',
            },
        ),
    ]
