# Generated by Django 3.0.1 on 2019-12-24 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='createmeeting',
            table='meetings',
        ),
    ]
