# Generated by Django 3.0.1 on 2019-12-26 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('start_meeting', '0002_auto_20191225_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordRecognize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(blank=True)),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_meeting.CreateMeeting')),
            ],
            options={
                'db_table': 'keyword_recognization',
            },
        ),
    ]
