# Generated by Django 3.0.1 on 2019-12-24 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('start_meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_id', models.IntegerField()),
                ('text', models.TextField()),
                ('entities', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('sentiments', models.TextField(blank=True)),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_meeting.CreateMeeting')),
            ],
        ),
    ]
