# Generated by Django 3.0.1 on 2020-01-30 19:55

from django.db import migrations, models
import file_upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=file_upload.models.get_file_path)),
                ('meeting_id', models.TextField()),
                ('file_url', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('waveform', models.TextField()),
            ],
            options={
                'db_table': 'file-url',
            },
        ),
    ]
