# Generated by Django 3.0.1 on 2020-01-30 17:17

from django.db import migrations, models
import django.db.models.deletion
import file_upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('start_meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=file_upload.models.get_file_path)),
                ('file_url', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_meeting.CreateMeeting')),
            ],
            options={
                'db_table': 'file-url',
            },
        ),
    ]
