# Generated by Django 3.0.1 on 2019-12-28 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('start_meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recognise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entities', models.TextField(blank=True)),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_meeting.CreateMeeting')),
            ],
            options={
                'db_table': 'entity_recognisation',
            },
        ),
    ]
