# Generated by Django 3.0.1 on 2019-12-25 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity_recognisation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recognise',
            name='text',
        ),
    ]
